sudo: false
language: rust
matrix:
  include:
    - rust: nightly
      env: TEST_SUITE=suite_nightly
    - rust: beta
      env: TEST_SUITE=suite_beta
    - rust: stable
      env: TEST_SUITE=suite_stable
  allow_failures:
    - rust: nightly
    - rust: beta
script:
    - rustc --version
    - cargo --version
    - cargo build --verbose
    - cargo build --verbose --features arbitrary
    - cargo build --verbose --features serde-serialize
    - cargo test --verbose --features "arbitrary debug serde-serialize"
